// Code generated by "stringer -type=ContractState -trimprefix=ContractState"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContractStateNone-0]
	_ = x[ContractStateComplete-1]
	_ = x[ContractStateError-2]
}

const _ContractState_name = "NoneCompleteError"

var _ContractState_index = [...]uint8{0, 4, 12}

func (i ContractState) String() string {
	if i < 0 || i >= ContractState(len(_ContractState_index)-1) {
		return "ContractState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContractState_name[_ContractState_index[i]:_ContractState_index[i+1]]
}
